version: "3.8"

services:
  postgres:
    image: "bitnami/postgresql:latest"
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=vitly

  redis:
    image: "bitnami/redis:latest"
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
