name: CI/CD Pipeline - Vitly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql:latest
        env:
          POSTGRES_USER: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: vitly
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U docker"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: bitnami/redis:latest
        env:
          REDIS_PASSWORD: docker
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Checagem do código (compilação TS)
        run: npx tsc --noEmit

      - name: Executar script de setup
        run: npm run setup

      - name: Executar testes automatizados com Vitest
        run: npm run test

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da imagem Docker
        run: docker build -t vmadalosso/vitly:latest .

      - name: Push da imagem Docker para o Docker Hub
        run: docker push vmadalosso/vitly:latest
